-- What is the total revenue generated by female versus male customers?
select 
gender,sum(purchase_amount) as total_revenue
from
customer 
group by 
gender;




-- Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,category,purchase_amount
from 
customer 
where 
discount_applied = 'Yes' AND 
purchase_amount > ( 
select avg(purchase_amount) from customer);



-- Which are the top five products with the highest average review rating? 
select 
item_purchased , Round(avg(review_rating :: numeric),2) as avg_review_rating
from 
customer  
group by 
item_purchased
order by 
avg_review_rating desc 
limit 5;


-- compare the average purchase amounts  between standard and express shipping?
select 
shipping_type,ROUND(avg(purchase_amount),2) as Average_Purchase_Price
from 
customer  
where 
shipping_type   in ('Standard', 'Express')
group by 
shipping_type 



-- Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers.
select 
subscription_status, count(customer_id) as customer_count ,round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from 
customer 
group by 
subscription_status;


-- Which five products have the highest percentage of purchases with discounts applied? 
select 
item_purchased, (100 * sum (
case when discount_applied = 'Yes' then 1 else  0 end
)/count(*)) as discount_rate 
from 
customer  
group by 
item_purchased 
order by 
discount_rate desc
limit 5;


-- Segment customers into new, returning, and loyal based on their total number of purchases. 

with segment_type as (
select customer_id,previous_purchases,
case  
    when previous_purchases  = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else  'Loyal'
	end as customer_segment
from 
customer 
) 

select customer_segment , count(customer_id) as total_number_of_purchases
from segment_type 
group by  
customer_segment;


-- What are the top three purchased products within each category? 
--  what is the revenue contribution by age group 
select 
age_criteria,sum(purchase_amount) as revenue_contribution
from 
customer 
group by 
age_criteria;

--- are repeat buyyers( more than 5 times) are likely to subscribe   from repe
select 
subscription_status,count(customer_id)
from 
customer 
where 
previous_purchases between 2 and 10
group by 
subscription_status;
